version: '3.4'

services:
  eshop.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  eshopapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

