version: '3.4'

networks:
  backend:

services:
  eshopdb:
    container_name: eshop-dbcontainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pa@2or$%%dd
    networks:
      - backend
    ports:
      - 7170:1433 

  # basketdb:
  #   container_name: basket-dbcontainer
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=ttr%$s+65Y22#
  #   networks:
  #     - backend
  #   ports:
  #     - 7077:1433

  eshop.api:
    container_name: eshopapi-container
    image: ${DOCKER_REGISTRY-}eshopapi
    build:
      context: .
      dockerfile: src/ServiceOne/EShop.API/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=eshopdb
      - DB_NAME=EShopDb
      - DB_SA_PASSWORD=pa@2or$%%dd
  
  eshopapigateway:
    image: ${DOCKER_REGISTRY-}eshopapigateway
    build:
      context: .
      dockerfile: src/Gateway/EShopApiGateway/Dockerfile
    ports:
      - 7180:80    
    networks:
      - backend



  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/ServiceTwo/Basket.API/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=eshopdb
      - DB_NAME=BasketDatabase
      - DB_SA_PASSWORD=pa@2or$%%dd


  authenticationwebapi:
    container_name: authentication-webapi
    image: ${DOCKER_REGISTRY-}authenticationwebapi
    build:
      context: .
      dockerfile: src/AuthenticationLayer/AuthenticationWebAPi/Dockerfile
    networks:
      - backend

